apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: t6go21dny-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:efaf8dd215f94302bab6ec1fc35f0e9f3bcd1ba7@sha256:6cc3069e476f20a51877fe1805deabd0fee4c3e413308c6a823e3d425bb33403
          name: container-image
